In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib as plt
from sqlalchemy import create_engine # 导入引擎对象

# Pandas操作csv文件

In [3]:
# 读取csv文件，获取数据
"""
参1：文件路径
参2： 分割符
参3：读取的列名
"""
df = pd.read_csv("/Users/yiruihe/Desktop/python/machine_learningProject/stock_day.csv",sep= ',', usecols = ['open','high','close','low'])
df

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48
...           ...    ...    ...    ...
2015-03-06  13.17  14.48  14.28  13.13
2015-03-05  12.88  13.45  13.16  12.87
2015-03-04  12.80  12.92  12.90  12.61
2015-03-03  12.52  13.06  12.70  12.52
2015-03-02  12.25  12.67  12.52  12.20

[643 rows x 4 columns]

In [4]:
# 拿到前10条，写到文件中
df[:10].to_csv('/Users/yiruihe/Desktop/python/machine_learningProject/my_file1.csv',sep= ',',index = False)

In [5]:
# 3. 特殊的csv文件 → tsv文件。
# 区别：csv文件 → 以,做分割， tsv文件 → 足以tab键分隔的。
df[:5].to_csv('/Users/yiruihe/Desktop/python/machine_learningProject/my_file2.tsv', sep='\t', index=True)
print('写入成功！')

写入成功！

In [6]:
# 4. 读取tsv文件。
df2 = pd.read_csv('/Users/yiruihe/Desktop/python/machine_learningProject/my_file2.tsv', sep='\t')
df2

   Unnamed: 0   open   high  close    low
0  2018-02-27  23.53  25.88  24.16  23.53
1  2018-02-26  22.80  23.78  23.53  22.80
2  2018-02-23  22.88  23.37  22.82  22.71
3  2018-02-22  22.25  22.76  22.28  22.02
4  2018-02-14  21.49  21.99  21.92  21.48

In [7]:
# 4. 读取tsv文件。
# 参1：文件路径，参2：分隔符，参3：把索引为0的列(第1列) 设置为索引。
df2 = pd.read_csv('/Users/yiruihe/Desktop/python/machine_learningProject/my_file2.tsv', sep='\t', index_col=0)
df2

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48

# Pandas操作MySQL数据表

In [8]:
# 前提：你的Anaconda要先装：pymysql 和 sqlalchemy 模块。
# 安装方式：pip install 模块名
# 此外，你的电脑还需要安装：mysql数据库

In [9]:
"""
UTF-8：国际通用编码。包含全球所有国家的文字（英文、中文、日文、emoji表情等）。在 Python / Pandas 中，默认就是 UTF-8。
GBK：中国本地专用编码。主要针对简体中文设计，不包含日文、韩文、emoji 等。
index_col=0 让第一列充当索引
"""
# 需求：把这些数据写到MYSQL中
data = pd.read_csv('/Users/yiruihe/Desktop/python/machine_learningProject/csv示例文件.csv',encoding='gbk',index_col=0)
data

     birthday name   AKA
0    1960/5/7  刘海柱  职业法师
1    1978/9/1  赵金龙   大力哥
2  1984/12/27  周立齐  窃格瓦拉
3   1969/1/24   于谦  相声皇后

In [10]:
# 导包
# from sqlalchemy import create_engine # 导入引擎对象 写到第一个单元格了

In [11]:
# 创建引擎对象
#                      数据库+模块名：//数据库用户名user：密码@主机名host:端口号/要操作的数据库？编码方式
engine = create_engine('mysql+pymysql://root:password@localhost:3306/Test3?charset=utf8')

# 具体的往数据库写数据的动作
# 参1：数据表名 参2：引擎对象 参3：是否把索引写入数据库， 参4：如果数据表存在，则如何处理
data.to_sql('my_table',engine,index=False,if_exists='replace')

4

In [12]:
# 从SQL表中读取数据
# 参1：数据表名， 参2： 引擎对象
sql_df = pd.read_sql('my_table',engine) #读取全表
sql_df = pd.read_sql('select name, AKA from my_table limit 0,2',engine) # 读取表中指定数据
sql_df

  name   AKA
0  刘海柱  职业法师
1  赵金龙   大力哥